complete -c conceal -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c conceal -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c conceal -n "__fish_use_subcommand" -f -a "list" -d 'List all the discarded entities'
complete -c conceal -n "__fish_use_subcommand" -f -a "restore" -d 'Restore entities discarded under the current directory'
complete -c conceal -n "__fish_use_subcommand" -f -a "clean" -d 'Delete all the discarded entities permanently'
complete -c conceal -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c conceal -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c conceal -n "__fish_seen_subcommand_from restore" -s h -l help -d 'Print help'
complete -c conceal -n "__fish_seen_subcommand_from clean" -s h -l help -d 'Print help'
complete -c conceal -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all the discarded entities'
complete -c conceal -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "restore" -d 'Restore entities discarded under the current directory'
complete -c conceal -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "clean" -d 'Delete all the discarded entities permanently'
complete -c conceal -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
