complete -c cnc -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c cnc -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c cnc -n "__fish_use_subcommand" -f -a "put" -d '[default] Throw the files in the trash bin'
complete -c cnc -n "__fish_use_subcommand" -f -a "list" -d 'List all the discarded files'
complete -c cnc -n "__fish_use_subcommand" -f -a "restore" -d 'Restore files discarded under the current directory'
complete -c cnc -n "__fish_use_subcommand" -f -a "empty" -d 'Delete all the discarded files permanently'
complete -c cnc -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c cnc -n "__fish_seen_subcommand_from put" -s h -l help -d 'Print help'
complete -c cnc -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c cnc -n "__fish_seen_subcommand_from restore" -s h -l help -d 'Print help'
complete -c cnc -n "__fish_seen_subcommand_from empty" -s h -l help -d 'Print help'
complete -c cnc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from put; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from empty; and not __fish_seen_subcommand_from help" -f -a "put" -d '[default] Throw the files in the trash bin'
complete -c cnc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from put; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from empty; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all the discarded files'
complete -c cnc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from put; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from empty; and not __fish_seen_subcommand_from help" -f -a "restore" -d 'Restore files discarded under the current directory'
complete -c cnc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from put; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from empty; and not __fish_seen_subcommand_from help" -f -a "empty" -d 'Delete all the discarded files permanently'
complete -c cnc -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from put; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from restore; and not __fish_seen_subcommand_from empty; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
